### ISSUE TITLE
 No module named 'version', Python versioning issue? 

### ISSUE THREAD

**Issue by caffeine-potent** [iiSeymour/nbtop#11]
### Error:  
```ImportError: No module named 'version'```  
  
### How to recreate:  
```  
pip install nbtop  
nbtop --help  
```   
  
### System info:   

Python version `3.52`

**Comment by iiSeymour** [comment]
Fixed and pushed 0.5.1 to pypi, thanks.

**Comment by caffeine-potent** [comment]
`nbtop --help` works now. Thanks!
