### ISSUE TITLE
Trouble installing nbtop

### ISSUE THREAD

**Issue by sungreong** [iiSeymour/nbtop#15]
Hello I want to use the nbtop.

so I install it, but say

>  nbtop : command not found

how I solve it?

Thanks

![image](https://user-images.githubusercontent.com/22166391/61771235-43270180-ae2a-11e9-9b00-c699d3b38ea9.png)

**Comment by iiSeymour** [comment]
If you installed using `pip install --user nbtop` then `nbtop` will only be installed for that user that was used to do the install and will end up in `$USER/.local/bin/nbtop`.

If you want a system-wide install then run `sudo pip install nbtop` which will install to `/usr/local/bin/nbtop`.
