### ISSUE TITLE
No kernels/notebooks listed

### ISSUE THREAD

**Issue by tqfjo** [iiSeymour/nbtop#16]
When I run `nbtop` I get an empty list.

This sounds similar to https://github.com/iiSeymour/nbtop/issues/6 but:
* I have not explicitly set a password
* I tried pasting the jupyter server token in to `-p` and get `invalid password!` back
* I also tried all combinations of password vs no password and `-k` vs no `-k` -- same results

This is what my inputs with `-p` look like:
```
$ jupyter notebook list
Currently running servers:
http://localhost:8888/?token=741228bd581ec74444a32c3baeef7c695ea79b6a2daf63ac :: /home/user/repos/calls

$ nbtop -p -u http://localhost:8888                                                                             
password for http://localhost:8888:
invalid password!

$ nbtop -k -p -u http://localhost:8888                                                                          
password for http://localhost:8888:
invalid password!

$ python --version
Python 3.7.2
```

I'm running this all in a `conda` environment.

This looks incredibly useful by the way -- thanks.

**Comment by iiSeymour** [comment]
What about..

```
$ nbtop -u http://localhost:8888/?token=741228bd581ec74444a32c3baeef7c695ea79b6a2daf63ac
```

**Comment by tqfjo** [comment]
Same results (I tried w/ and w/o `-p` and `-k` as well just to see)

**Comment by tqfjo** [comment]
Passing `--debug` as well just shows me this line alone at the top of the terminal (and I have to `C-c` out of it):
```
Kernel                                  CPU % MEM %     Notebook
```

**Comment by iiSeymour** [comment]
Passing the token as the password works in version `0.6.0` which I've just pushed to PyPI.
