### ISSUE TITLE
CPU, MEM -99%??

### ISSUE THREAD

**Issue by sungreong** [iiSeymour/nbtop#17]
![image](https://user-images.githubusercontent.com/22166391/74999052-e19d4300-549d-11ea-86a1-af20872f169e.png)

I find the bug.
please fix this :)

**Comment by iiSeymour** [comment]
From the README:

> nbtop uses the kernel ids of running notebooks (queried from /api/sessions) and matches them to running processes on the server. If nbtop is pointed at a remote notebook server the memory and cpu percentage will be displayed as -99.
