### ISSUE TITLE
Push latest version to PyPI?

### ISSUE THREAD

**Issue by robintw** [iiSeymour/nbtop#5]
Hi @iiSeymour,

Is it possible to push the latest version of nbtop (0.3.2) to PyPI so that it can be installed easily through 'pip install'?

I've got some colleagues who'd like to use the absolute memory usage functionality that I added, but have issues installing from anywhere apart from PyPI.

Cheers,

Robin

**Comment by iiSeymour** [comment]
Sorry, I should have remembered to push the most recent changes. [0.3.2](https://pypi.python.org/pypi/nbtop/0.3.2) is now available from PyPI.
