### ISSUE TITLE
nbtop shows no info if notebook server has a password

### ISSUE THREAD

**Issue by OlympusMonds** [iiSeymour/nbtop#6]
I have a password set on my jupyter server, and when I run nbtop, I just get an empty list.
It looks like this is because in session_state the response.json() fails silently when it tries to decode the html for accepting a password.

Any help would be much appreciated!

**Comment by iiSeymour** [comment]
For password protected notebook servers you can now use the options `-p` or `--passwd`. Providing one of these flags will trigger a password prompt _(the flag doesn't take any arguments)_. Pull the latest commits from master and let me know if you have any issues.

**Comment by OlympusMonds** [comment]
Yeah, this works with IPython notebooks. It fails with Jupyter Notebooks (4.0.4), because /api gives a 404 - even though from this: https://github.com/jupyter/notebook/commit/ad25d338087dc72ba8f2d6835f3e1d12f9aeccef it probably shouldn't!
Anyway, it's a separate issue - the fix you put in for passwords works great!

**Comment by iiSeymour** [comment]
Great.

I have raised #7 for the server version issue.
