### ISSUE TITLE
Trouble running nb-top in Tmux

### ISSUE THREAD

**Issue by caffeine-potent** [iiSeymour/nbtop#8]
Hi iiSeymour,  

I'm running into an issue while running **nbtop** in **t-mux**.   
I have two screens open, a **htop** session, and a session in which I'd like to run **nbtop**.  
When I run nbtop on localhost I get the following error

    _curses.error: addstr() returned ERR
  

![issue](https://cloud.githubusercontent.com/assets/20566665/22440319/f0208c4c-e700-11e6-8ae9-9a069d7a2f8a.png)

**Comment by iiSeymour** [comment]
This error will be seen because `nbtop` is trying to write the notebook name outside the terminal boundaries and won't be limited to running in a tmux session. You shouldn't have any issues if you make your terminal emulator wider.

A proper fix will be to add support for horizontal scrolling.

**Comment by caffeine-potent** [comment]
Thanks. I'll close this issue for now.
